version: "3.7"

services:

  mysql:
    image: mysql:8.0.30
    container_name: db-mysql
    environment:
      MYSQL_DATABASE: 'transportapp'
      MYSQL_USER: 'transportapp'
      MYSQL_PASSWORD: 'TransPortApp2022*'
      MYSQL_ROOT_PASSWORD: 'TransPortApp2022*'
    networks:
      - net
    ports:
      - '13306:3306'
    volumes:
      - mysql_data:/var/lib/mysql

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '18080:8080'

    command: java -Djava.security.egd=file:/dev/./urandom -jar /project/build/libs/TransportApp-1.0-SNAPSHOT.jar
    networks:
      - net
    depends_on:
      - mysql
volumes:
  mysql_data:
networks:
  net:




